First_name = input("enter the first name") 
last_name = input("enter the last name")
monthly_salary = float(input("enter the monthly salary"))
apparisel_salary= (monthly_salary*15)/100
total_salary = apparisel_salary + monthly_salary 
print( " " * 25 + "~" * 5 + "*" * 20 + "~" * 5 + " " * 25 )
print("-" * 80 )
print(" " * 80 )
print(" " * 28 + "SALARY APPARISEL LETTER" + " " * 29)
print(" " * 80 )
print("-" * 80 )
print(" " * 3 + "February 1,2019" + " " * 62)
print(" " * 3 + "{:<12}".format(First_name) + " " * 65)
print(" " * 3 + "{:<30}".format("Junior Technical Operator") + " " * 47)
print(" " * 80 )
print(" " * 3 + "{:<5}".format("Dear,") + " " * 72)
print(" " * 3 + "Last year with a lot's of growth and achievements at our company including)")
print(" " * 3 + "(establishment of relations with new clients,ontime delivery of product).")
print(" " * 3 + "The future holds lot of promises and we are happy to have you as a part of")
print(" " * 3 + "our team .")
print(" " * 3 + "we are happy with your performance and are equally to share you that you ")
print(" " * 3 + "have been promoted to SENIOR TECHNICAL OPERATORE .")
print(" " * 3 + "your new compansetion structure is as follows:")
print(" " * 80)
print(" " * 3 + "|" + "-" * 75 + "|" )
print(" " * 3 +  "|" + " " * 75 + "|" )
print(" " * 3 + "|" + "{:<25}".format("Compensation Head") + "|" + "{:^23}".format("Existing") + "|" + "{:>25}".format("Increment") + "|")
print(" " * 3 + "|" + "-" * 75 + "|" )
print(" " * 3 + "|" + " " * 75 + "|" )
print(" " * 3 + "|" + "{:^25}".format("Salary") + "|" + "{:^23}".format(monthly_salary) + "|" + "{:>25}".format(apparisel_salary) + "|")
print(" " * 3 + "|" + " " * 25 + "|" + " " * 23 + "|" + " " * 25 + "|" )
print(" " * 3 + "|" + "-" * 75 + "|" )
print(" " * 3 + "|" + " " * 25 + "|" + " " * 23 + "|" + "{:>25}".format(total_salary) + "|" )
print(" " * 3 + "|" + "-" * 75 + "|" )
print(" " * 80)
print(" " * 3 + " We look forward to even greater contribution from you in the future" )
print(" " * 80)
print(" " * 3 + " Manager HR")




